# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame = QtWidgets.QLabel(self.centralwidget)
        self.Frame.setGeometry(QtCore.QRect(3, 41, 521, 371))
        self.Frame.setText("")
        self.Frame.setObjectName("Frame")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 39, 191, 511))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_creat = QtWidgets.QPushButton(self.groupBox)
        self.btn_creat.setGeometry(QtCore.QRect(10, 10, 51, 23))
        self.btn_creat.setObjectName("btn_creat")
        self.btn_delete = QtWidgets.QPushButton(self.groupBox)
        self.btn_delete.setGeometry(QtCore.QRect(70, 10, 51, 23))
        self.btn_delete.setObjectName("btn_delete")
        self.btn_save = QtWidgets.QPushButton(self.groupBox)
        self.btn_save.setGeometry(QtCore.QRect(130, 10, 51, 23))
        self.btn_save.setObjectName("btn_save")
        self.listObj = QtWidgets.QListWidget(self.groupBox)
        self.listObj.setGeometry(QtCore.QRect(10, 40, 171, 331))
        self.listObj.setObjectName("listObj")
        self.check_auto = QtWidgets.QCheckBox(self.groupBox)
        self.check_auto.setGeometry(QtCore.QRect(20, 390, 71, 16))
        self.check_auto.setObjectName("check_auto")
        self.check_return = QtWidgets.QCheckBox(self.groupBox)
        self.check_return.setGeometry(QtCore.QRect(20, 420, 81, 16))
        self.check_return.setObjectName("check_return")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 731, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 731, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_kpsb = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_kpsb.setAutoFillBackground(True)
        self.btn_kpsb.setObjectName("btn_kpsb")
        self.horizontalLayout.addWidget(self.btn_kpsb)
        self.btn_kpgz = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_kpgz.setObjectName("btn_kpgz")
        self.horizontalLayout.addWidget(self.btn_kpgz)
        self.btn_rlsb = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_rlsb.setAutoFillBackground(True)
        self.btn_rlsb.setObjectName("btn_rlsb")
        self.horizontalLayout.addWidget(self.btn_rlsb)
        self.btn_bqsb = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_bqsb.setAutoFillBackground(True)
        self.btn_bqsb.setObjectName("btn_bqsb")
        self.horizontalLayout.addWidget(self.btn_bqsb)
        self.btn_mbgz = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_mbgz.setAutoFillBackground(True)
        self.btn_mbgz.setObjectName("btn_mbgz")
        self.horizontalLayout.addWidget(self.btn_mbgz)
        self.btn_lxkpsb = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_lxkpsb.setAutoFillBackground(True)
        self.btn_lxkpsb.setObjectName("btn_lxkpsb")
        self.horizontalLayout.addWidget(self.btn_lxkpsb)
        self.btn_changeCap = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_changeCap.setEnabled(True)
        self.btn_changeCap.setAutoFillBackground(False)
        self.btn_changeCap.setAutoDefault(False)
        self.btn_changeCap.setDefault(False)
        self.btn_changeCap.setFlat(False)
        self.btn_changeCap.setObjectName("btn_changeCap")
        self.horizontalLayout.addWidget(self.btn_changeCap)
        self.btn_restart = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_restart.setObjectName("btn_restart")
        self.horizontalLayout.addWidget(self.btn_restart)
        self.list_msg = QtWidgets.QListWidget(self.centralwidget)
        self.list_msg.setGeometry(QtCore.QRect(0, 430, 541, 121))
        self.list_msg.setObjectName("list_msg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_creat.setText(_translate("MainWindow", "创建"))
        self.btn_delete.setText(_translate("MainWindow", "删除"))
        self.btn_save.setText(_translate("MainWindow", "保存"))
        self.check_auto.setText(_translate("MainWindow", "自动模式"))
        self.check_return.setText(_translate("MainWindow", "回传服务器"))
        self.btn_kpsb.setText(_translate("MainWindow", "卡片识别"))
        self.btn_kpgz.setText(_translate("MainWindow", "卡片跟踪"))
        self.btn_rlsb.setText(_translate("MainWindow", "人脸识别"))
        self.btn_bqsb.setText(_translate("MainWindow", "表情识别"))
        self.btn_mbgz.setText(_translate("MainWindow", "目标跟踪"))
        self.btn_lxkpsb.setText(_translate("MainWindow", "连续卡片识别"))
        self.btn_changeCap.setText(_translate("MainWindow", "切换视频源"))
        self.btn_restart.setText(_translate("MainWindow", "重启"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))

